INSERT INTO cliente
            (id,
             codigo_unico,
             nombres,
             apellidos,
             tipo_documento,
             numero_documento,
             fecha_registro)
VALUES      ( '1',
              '01HT46433296',
              'HENRRI ROGGER SEGUNDO',
              'TRUJILLO ROMERO',
              '01',
              '46433296',
              Now () ),
            ( '2',
              '01EC76761195',
              'ELVA RAQUEL',
              'CERON MELENDEZ',
              '01',
              '76761195',
              Now () ),
            ( '3',
              '0002232',
              'ARIADNA CER',
              'CERON MELENDEZ',
              '01',
              '5554545',
              Now () ),
            ( '4',
              '2512121DWDW',
              'ROCIO',
              'CHOOQUE ZETA',
              '02',
              '54545456',
              Now () ); 